### ISSUE TITLE
witch node version is required?

### ISSUE THREAD

**Issue by Veldhuis123** [savareyhano/sistem-informasi-inventaris-barang#85]
i have this problems. ubuntu 24.04

Cloning into 'Sistem-Informasi-Inventaris-Barang'...
remote: Enumerating objects: 3152, done.
remote: Counting objects: 100% (1975/1975), done.
remote: Compressing objects: 100% (1505/1505), done.
remote: Total 3152 (delta 660), reused 563 (delta 467), pack-reused 1177 (from 1)
Receiving objects: 100% (3152/3152), 18.97 MiB | 12.03 MiB/s, done.
Resolving deltas: 100% (1021/1021), done.
root@magazijnbeheer:/home/administrator# cd Sistem-Informasi-Inventaris-Barang
root@magazijnbeheer:/home/administrator/Sistem-Informasi-Inventaris-Barang# cp .env.example .env
root@magazijnbeheer:/home/administrator/Sistem-Informasi-Inventaris-Barang# npm install
npm WARN deprecated bootstrap-colorpicker@3.4.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated flag-icon-css@4.1.7: The project has been renamed to flag-icons
npm ERR! code 1
npm ERR! path /home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
npm ERR! Failed to execute '/usr/bin/node /usr/share/nodejs/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v109' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@18.19.1 | linux | x64
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v109-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v109-linux-glibc-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@18.19.1 (node-v109 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v109-linux-glibc-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@18.19.1 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@18.19.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.12.3 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/include/nodejs/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: 1: pkg-config: not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:329:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm ERR! gyp ERR! System Linux 6.8.0-45-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/share/nodejs/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v109"
npm ERR! gyp ERR! cwd /home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas
npm ERR! gyp ERR! node -v v18.19.1
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/share/nodejs/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v109' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
npm ERR! node-pre-gyp ERR! System Linux 6.8.0-45-generic
npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
npm ERR! node-pre-gyp ERR! cwd /home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v18.19.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-10-07T19_41_57_882Z-debug-0.log

**Comment by savareyhano** [comment]
> i have this problems. ubuntu 24.04
> 
> Cloning into 'Sistem-Informasi-Inventaris-Barang'... remote: Enumerating objects: 3152, done. remote: Counting objects: 100% (1975/1975), done. remote: Compressing objects: 100% (1505/1505), done. remote: Total 3152 (delta 660), reused 563 (delta 467), pack-reused 1177 (from 1) Receiving objects: 100% (3152/3152), 18.97 MiB | 12.03 MiB/s, done. Resolving deltas: 100% (1021/1021), done. root@magazijnbeheer:/home/administrator# cd Sistem-Informasi-Inventaris-Barang root@magazijnbeheer:/home/administrator/Sistem-Informasi-Inventaris-Barang# cp .env.example .env root@magazijnbeheer:/home/administrator/Sistem-Informasi-Inventaris-Barang# npm install npm WARN deprecated bootstrap-colorpicker@3.4.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info. npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1 npm WARN deprecated flag-icon-css@4.1.7: The project has been renamed to flag-icons npm ERR! code 1 npm ERR! path /home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas npm ERR! command failed npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary npm ERR! Failed to execute '/usr/bin/node /usr/share/nodejs/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v109' (1) npm ERR! node-pre-gyp info it worked if it ends with ok npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11 npm ERR! node-pre-gyp info using node@18.19.1 | linux | x64 npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v109-linux-glibc-x64.tar.gz npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v109-linux-glibc-x64.tar.gz npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@18.19.1 (node-v109 ABI, glibc) (falling back to source compile with node-gyp) npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v109-linux-glibc-x64.tar.gz npm ERR! gyp info it worked if it ends with ok npm ERR! gyp info using node-gyp@9.3.0 npm ERR! gyp info using node@18.19.1 | linux | x64 npm ERR! gyp info ok npm ERR! gyp info it worked if it ends with ok npm ERR! gyp info using node-gyp@9.3.0 npm ERR! gyp info using node@18.19.1 | linux | x64 npm ERR! gyp info find Python using Python version 3.12.3 found at "/usr/bin/python3" npm ERR! gyp info spawn /usr/bin/python3 npm ERR! gyp info spawn args [ npm ERR! gyp info spawn args '/usr/share/nodejs/node-gyp/gyp/gyp_main.py', npm ERR! gyp info spawn args 'binding.gyp', npm ERR! gyp info spawn args '-f', npm ERR! gyp info spawn args 'make', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args '/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/config.gypi', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args '/usr/share/nodejs/node-gyp/addon.gypi', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args '/usr/include/nodejs/common.gypi', npm ERR! gyp info spawn args '-Dlibrary=shared_library', npm ERR! gyp info spawn args '-Dvisibility=default', npm ERR! gyp info spawn args '-Dnode_root_dir=/usr/include/nodejs', npm ERR! gyp info spawn args '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp', npm ERR! gyp info spawn args '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib', npm ERR! gyp info spawn args '-Dmodule_root_dir=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas', npm ERR! gyp info spawn args '-Dnode_engine=v8', npm ERR! gyp info spawn args '--depth=.', npm ERR! gyp info spawn args '--no-parallel', npm ERR! gyp info spawn args '--generator-output', npm ERR! gyp info spawn args 'build', npm ERR! gyp info spawn args '-Goutput_dir=.' npm ERR! gyp info spawn args ] npm ERR! /bin/sh: 1: pkg-config: not found npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp npm ERR! gyp ERR! configure error npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1 npm ERR! gyp ERR! stack at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:329:16) npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:517:28) npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:292:12) npm ERR! gyp ERR! System Linux 6.8.0-45-generic npm ERR! gyp ERR! command "/usr/bin/node" "/usr/share/nodejs/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v109" npm ERR! gyp ERR! cwd /home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas npm ERR! gyp ERR! node -v v18.19.1 npm ERR! gyp ERR! node-gyp -v v9.3.0 npm ERR! gyp ERR! not ok npm ERR! node-pre-gyp ERR! build error npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/share/nodejs/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v109' (1) npm ERR! node-pre-gyp ERR! stack at ChildProcess. (/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23) npm ERR! node-pre-gyp ERR! stack at ChildProcess.emit (node:events:517:28) npm ERR! node-pre-gyp ERR! stack at maybeClose (node:internal/child_process:1098:16) npm ERR! node-pre-gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:303:5) npm ERR! node-pre-gyp ERR! System Linux 6.8.0-45-generic npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary" npm ERR! node-pre-gyp ERR! cwd /home/administrator/Sistem-Informasi-Inventaris-Barang/node_modules/canvas npm ERR! node-pre-gyp ERR! node -v v18.19.1 npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11 npm ERR! node-pre-gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2024-10-07T19_41_57_882Z-debug-0.log

It's an issue with node-canvas package for linux, the solution is you can either remove the node-canvas by npm uninstall then try to install again, or install the node-canvas dependency like this:

```
RUN apk add --update --no-cache \
    make \
    g++ \
    jpeg-dev \
    cairo-dev \
    giflib-dev \
    pango-dev \
    libtool \
    autoconf \
    automake
```

OR run the project with docker, there's an unmerged docker branch called 'feat/docker', to run, it should be pretty straightforward 'docker compose up -d'

**Comment by Veldhuis123** [comment]
the installation is ready but i have 1 problem. he can't fount the bootstrap.

GET / 200 2044 - 44.824 ms
GET /plugins/fontawesome-free/css/all.min.css 404 601 - 6.615 ms
GET /plugins/icheck-bootstrap/icheck-bootstrap.min.css 404 601 - 3.964 ms
GET /plugins/jquery/jquery.min.js 404 601 - 1.852 ms
GET /plugins/bootstrap/js/bootstrap.bundle.min.js 404 601 - 2.443 ms
GET / 304  - 5.348 ms
GET /plugins/fontawesome-free/css/all.min.css 404 601 - 1.477 ms
GET /plugins/icheck-bootstrap/icheck-bootstrap.min.css 404 601 - 1.774 ms
GET /plugins/jquery/jquery.min.js 404 601 - 2.028 ms
GET /plugins/bootstrap/js/bootstrap.bundle.min.js 404 601 - 2.008 ms
GET / 304  - 2.701 ms
GET /plugins/fontawesome-free/css/all.min.css 404 601 - 1.982 ms
GET /plugins/icheck-bootstrap/icheck-bootstrap.min.css 404 601 - 1.949 ms
GET /plugins/bootstrap/js/bootstrap.bundle.min.js 404 601 - 1.413 ms
GET /plugins/jquery/jquery.min.js 404 601 - 1.889 ms
POST /login 302 30 - 188.994 ms
GET / 200 11345 - 60.082 ms
GET /plugins/fontawesome-free/css/all.min.css 404 601 - 1.390 ms
GET /plugins/select2/css/select2.min.css 404 601 - 1.669 ms
GET /plugins/datatables-bs4/css/dataTables.bootstrap4.min.css 404 601 - 1.783 ms
GET /plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css 404 601 - 1.575 ms
GET /plugins/jquery/jquery.min.js 404 601 - 1.591 ms
GET /plugins/datatables-responsive/css/responsive.bootstrap4.min.css 404 601 - 1.745 ms
GET /plugins/bootstrap/js/bootstrap.bundle.min.js 404 601 - 1.503 ms
GET /plugins/datatables-buttons/css/buttons.bootstrap4.min.css 404 601 - 1.548 ms
GET /plugins/select2/js/select2.full.min.js 404 601 - 1.810 ms
GET /plugins/datatables/jquery.dataTables.min.js 404 601 - 1.563 ms
GET /plugins/datatables-bs4/js/dataTables.bootstrap4.min.js 404 601 - 1.558 ms
GET /plugins/datatables-responsive/js/dataTables.responsive.min.js 404 601 - 1.344 ms
GET /plugins/datatables-responsive/js/responsive.bootstrap4.min.js 404 601 - 1.585 ms
GET /plugins/datatables-buttons/js/dataTables.buttons.min.js 404 601 - 1.659 ms
GET /plugins/datatables-buttons/js/buttons.bootstrap4.min.js 404 601 - 2.023 ms
GET /plugins/jszip/jszip.min.js 404 601 - 4.904 ms
GET /plugins/pdfmake/pdfmake.min.js 404 601 - 1.707 ms
GET /plugins/pdfmake/vfs_fonts.js 404 601 - 1.709 ms
GET /plugins/datatables-buttons/js/buttons.html5.min.js 404 601 - 1.803 ms
GET /plugins/datatables-buttons/js/buttons.print.min.js 404 601 - 1.530 ms
GET /plugins/datatables-buttons/js/buttons.colVis.min.js 404 601 - 1.508 ms

i get a status 404

**Comment by savareyhano** [comment]
> the installation is ready but i have 1 problem. he can't fount the bootstrap.
> 
> GET / 200 2044 - 44.824 ms GET /plugins/fontawesome-free/css/all.min.css 404 601 - 6.615 ms GET /plugins/icheck-bootstrap/icheck-bootstrap.min.css 404 601 - 3.964 ms GET /plugins/jquery/jquery.min.js 404 601 - 1.852 ms GET /plugins/bootstrap/js/bootstrap.bundle.min.js 404 601 - 2.443 ms GET / 304 - 5.348 ms GET /plugins/fontawesome-free/css/all.min.css 404 601 - 1.477 ms GET /plugins/icheck-bootstrap/icheck-bootstrap.min.css 404 601 - 1.774 ms GET /plugins/jquery/jquery.min.js 404 601 - 2.028 ms GET /plugins/bootstrap/js/bootstrap.bundle.min.js 404 601 - 2.008 ms GET / 304 - 2.701 ms GET /plugins/fontawesome-free/css/all.min.css 404 601 - 1.982 ms GET /plugins/icheck-bootstrap/icheck-bootstrap.min.css 404 601 - 1.949 ms GET /plugins/bootstrap/js/bootstrap.bundle.min.js 404 601 - 1.413 ms GET /plugins/jquery/jquery.min.js 404 601 - 1.889 ms POST /login 302 30 - 188.994 ms GET / 200 11345 - 60.082 ms GET /plugins/fontawesome-free/css/all.min.css 404 601 - 1.390 ms GET /plugins/select2/css/select2.min.css 404 601 - 1.669 ms GET /plugins/datatables-bs4/css/dataTables.bootstrap4.min.css 404 601 - 1.783 ms GET /plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css 404 601 - 1.575 ms GET /plugins/jquery/jquery.min.js 404 601 - 1.591 ms GET /plugins/datatables-responsive/css/responsive.bootstrap4.min.css 404 601 - 1.745 ms GET /plugins/bootstrap/js/bootstrap.bundle.min.js 404 601 - 1.503 ms GET /plugins/datatables-buttons/css/buttons.bootstrap4.min.css 404 601 - 1.548 ms GET /plugins/select2/js/select2.full.min.js 404 601 - 1.810 ms GET /plugins/datatables/jquery.dataTables.min.js 404 601 - 1.563 ms GET /plugins/datatables-bs4/js/dataTables.bootstrap4.min.js 404 601 - 1.558 ms GET /plugins/datatables-responsive/js/dataTables.responsive.min.js 404 601 - 1.344 ms GET /plugins/datatables-responsive/js/responsive.bootstrap4.min.js 404 601 - 1.585 ms GET /plugins/datatables-buttons/js/dataTables.buttons.min.js 404 601 - 1.659 ms GET /plugins/datatables-buttons/js/buttons.bootstrap4.min.js 404 601 - 2.023 ms GET /plugins/jszip/jszip.min.js 404 601 - 4.904 ms GET /plugins/pdfmake/pdfmake.min.js 404 601 - 1.707 ms GET /plugins/pdfmake/vfs_fonts.js 404 601 - 1.709 ms GET /plugins/datatables-buttons/js/buttons.html5.min.js 404 601 - 1.803 ms GET /plugins/datatables-buttons/js/buttons.print.min.js 404 601 - 1.530 ms GET /plugins/datatables-buttons/js/buttons.colVis.min.js 404 601 - 1.508 ms
> 
> i get a status 404

Make sure the 'admin-lte' package is installed correctly, you can check if it's exist in this directory './node_modules/admin-lte/plugins'. If it's not try to run 'npm install again'
